name: CI

on:
  push:
    branches: [ master, feat/backend ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm ci
      - name: Generate Prisma client
        run: npm run prisma:generate
      - name: TypeScript compile
        run: npm run build
      - name: Lint
        run: npm run lint
      - name: Audit (production=false, level=high)
        run: npm audit --production=false --audit-level=high || true
      - name: Run tests
        env:
          NODE_ENV: test
        run: npm test -- --runInBand --detectOpenHandles
