name: CI

on:
  push:
    branches: [ master, feat/backend ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm ci
      - name: TypeScript compile
        run: npm run build
      - name: Lint
        run: npm run lint
